# Generated by Django 5.2.8 on 2025-11-13 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facility_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkplaceInitiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('qualification', '資質の向上'), ('work_style', '労働環境・処遇の改善'), ('balance', 'やりがい・働きがいの醸成')], max_length=20, verbose_name='区分')),
                ('item_number', models.CharField(max_length=10, verbose_name='項目番号')),
                ('description', models.TextField(verbose_name='取り組み内容')),
            ],
            options={
                'verbose_name': '職場環境等要件項目',
                'verbose_name_plural': '職場環境等要件項目',
                'ordering': ['category', 'item_number'],
            },
        ),
        migrations.CreateModel(
            name='ImprovementPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.IntegerField(default=2025, verbose_name='対象年度')),
                ('target_addition_tier', models.CharField(choices=[('I', '処遇改善加算I'), ('II', '処遇改善加算II'), ('III', '処遇改善加算III'), ('IV', '処遇改善加算IV')], max_length=3, verbose_name='申請する加算区分')),
                ('determined_addition_tier', models.CharField(blank=True, choices=[('I', '処遇改善加算I'), ('II', '処遇改善加算II'), ('III', '処遇改善加算III'), ('IV', '処遇改善加算IV')], max_length=3, verbose_name='判定された加算区分')),
                ('meets_career_path_1', models.BooleanField(default=False, verbose_name='キャリアパス要件I（職位・職責・職務内容等の要件）')),
                ('meets_career_path_2', models.BooleanField(default=False, verbose_name='キャリアパス要件II（資質向上のための計画）')),
                ('meets_career_path_3', models.BooleanField(default=False, verbose_name='キャリアパス要件III（経験・資格等に応じた昇給の仕組み）')),
                ('meets_career_path_4', models.BooleanField(default=False, verbose_name='キャリアパス要件IV（昇給以外の処遇改善の見える化）')),
                ('meets_career_path_5', models.BooleanField(default=False, verbose_name='キャリアパス要件V（介護福祉士の配置等）')),
                ('qualification_initiatives_count', models.IntegerField(default=0, verbose_name='資質の向上の取り組み数')),
                ('work_style_initiatives_count', models.IntegerField(default=0, verbose_name='労働環境・処遇の改善の取り組み数')),
                ('balance_initiatives_count', models.IntegerField(default=0, verbose_name='やりがい・働きがいの醸成の取り組み数')),
                ('total_service_units', models.BigIntegerField(default=0, help_text='前年度実績等から算出', verbose_name='総単位数（年間見込み）')),
                ('estimated_addition_amount', models.BigIntegerField(default=0, verbose_name='加算見込額（円/年）')),
                ('addition_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='加算率（%）')),
                ('total_salary_increase', models.BigIntegerField(default=0, verbose_name='賃金改善総額')),
                ('base_salary_increase', models.BigIntegerField(default=0, verbose_name='基本給の引き上げ')),
                ('allowance_increase', models.BigIntegerField(default=0, verbose_name='手当の引き上げ')),
                ('bonus_increase', models.BigIntegerField(default=0, verbose_name='賞与の引き上げ')),
                ('status', models.CharField(choices=[('draft', '作成中'), ('submitted', '提出済み'), ('approved', '承認済み'), ('rejected', '差し戻し')], default='draft', max_length=20, verbose_name='ステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提出日時')),
                ('notes', models.TextField(blank=True, verbose_name='備考・特記事項')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility_management.provider', verbose_name='事業者')),
                ('target_facilities', models.ManyToManyField(to='facility_management.facility', verbose_name='対象事業所')),
                ('workplace_initiatives', models.ManyToManyField(blank=True, to='plans.workplaceinitiative', verbose_name='実施する取り組み')),
            ],
            options={
                'verbose_name': '処遇改善計画書',
                'verbose_name_plural': '処遇改善計画書',
                'ordering': ['-fiscal_year', '-created_at'],
            },
        ),
    ]
