# Generated by Django 5.2.6 on 2025-09-19 13:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facility_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_code', models.CharField(choices=[('care', '介護職員'), ('nursing', '看護職員'), ('support', '生活相談員'), ('therapy', '機能訓練指導員'), ('nutrition', '栄養士'), ('admin', '事務職員'), ('other', 'その他')], max_length=20, unique=True, verbose_name='職種コード')),
                ('category_name', models.CharField(max_length=50, verbose_name='職種名')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria_name', models.CharField(max_length=100, verbose_name='評価項目名')),
                ('criteria_description', models.TextField(verbose_name='評価基準説明')),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=3, verbose_name='重み')),
                ('max_score', models.IntegerField(default=5, verbose_name='最高点')),
                ('job_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career_management.jobcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=50, verbose_name='職位名')),
                ('level', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='階層レベル')),
                ('required_experience_months', models.IntegerField(default=0, verbose_name='必要経験月数')),
                ('required_qualifications', models.TextField(blank=True, verbose_name='必要資格・要件')),
                ('job_description', models.TextField(blank=True, verbose_name='職務内容')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='facility_management.facility')),
                ('job_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career_management.jobcategory')),
            ],
            options={
                'ordering': ['job_category', 'level'],
                'unique_together': {('facility', 'job_category', 'level')},
            },
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=20, unique=True, verbose_name='職員番号')),
                ('name', models.CharField(max_length=100, verbose_name='氏名')),
                ('employment_status', models.CharField(choices=[('full_time', '正職員'), ('part_time', 'パート職員'), ('contract', '契約職員'), ('temp', '派遣職員')], max_length=20, verbose_name='雇用形態')),
                ('hire_date', models.DateField(verbose_name='入職日')),
                ('current_base_salary', models.IntegerField(default=0, verbose_name='現在の基本給')),
                ('current_total_salary', models.IntegerField(default=0, verbose_name='現在の総給与')),
                ('qualifications', models.TextField(blank=True, help_text='改行区切りで入力', verbose_name='保有資格')),
                ('qualification_acquisition_dates', models.TextField(blank=True, verbose_name='資格取得日')),
                ('latest_evaluation_score', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='最新評価点数')),
                ('latest_evaluation_date', models.DateField(blank=True, null=True, verbose_name='最新評価日')),
                ('is_active', models.BooleanField(default=True, verbose_name='在籍中')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='career_management.position')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='facility_management.facility')),
            ],
        ),
        migrations.CreateModel(
            name='StaffEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_period', models.CharField(help_text='例: 2025年上期', max_length=20, verbose_name='評価期間')),
                ('evaluation_date', models.DateField(verbose_name='評価日')),
                ('overall_score', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='総合評価点数')),
                ('overall_comment', models.TextField(blank=True, verbose_name='総合コメント')),
                ('evaluator_name', models.CharField(max_length=100, verbose_name='評価者名')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='career_management.staffmember')),
            ],
        ),
        migrations.CreateModel(
            name='PromotionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_date', models.DateField(verbose_name='昇格日')),
                ('promotion_type', models.CharField(choices=[('regular', '定期昇格'), ('special', '特別昇格'), ('lateral', '配置転換')], max_length=50, verbose_name='昇格種別')),
                ('salary_before', models.IntegerField(verbose_name='昇格前給与')),
                ('salary_after', models.IntegerField(verbose_name='昇格後給与')),
                ('reason', models.TextField(blank=True, verbose_name='昇格理由')),
                ('approved_by', models.CharField(max_length=100, verbose_name='承認者')),
                ('from_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_from', to='career_management.position')),
                ('to_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions_to', to='career_management.position')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='career_management.staffmember')),
            ],
        ),
        migrations.CreateModel(
            name='WageTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary_min', models.IntegerField(verbose_name='基本給（最低額）')),
                ('base_salary_max', models.IntegerField(verbose_name='基本給（最高額）')),
                ('qualification_allowance', models.IntegerField(default=0, verbose_name='資格手当')),
                ('position_allowance', models.IntegerField(default=0, verbose_name='職務手当')),
                ('annual_raise_amount', models.IntegerField(default=0, verbose_name='年間昇給額')),
                ('effective_date', models.DateField(verbose_name='適用開始日')),
                ('position', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wage_table', to='career_management.position')),
            ],
        ),
    ]
