# Generated by Django 5.2.6 on 2025-09-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wagetable',
            name='annual_raise_amount',
        ),
        migrations.RemoveField(
            model_name='wagetable',
            name='base_salary_max',
        ),
        migrations.RemoveField(
            model_name='wagetable',
            name='base_salary_min',
        ),
        migrations.RemoveField(
            model_name='wagetable',
            name='effective_date',
        ),
        migrations.AddField(
            model_name='wagetable',
            name='base_salary_start',
            field=models.PositiveIntegerField(default=0, verbose_name='初任給（1号）'),
        ),
        migrations.AddField(
            model_name='wagetable',
            name='max_steps',
            field=models.PositiveIntegerField(default=20, verbose_name='最大号数'),
        ),
        migrations.AddField(
            model_name='wagetable',
            name='step_raise_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='1号あたりの昇給額'),
        ),
        migrations.AlterField(
            model_name='wagetable',
            name='position_allowance',
            field=models.IntegerField(default=0, verbose_name='役職手当'),
        ),
    ]
