# Generated by Django 5.2.8 on 2025-11-13 06:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_management', '0002_remove_wagetable_annual_raise_amount_and_more'),
        ('facility_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerPathRequirementOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_qualifications', models.TextField(blank=True, help_text='例：介護福祉士、実務者研修修了者', verbose_name='必要資格')),
                ('required_experience_years', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='必要経験年数')),
                ('recommended_skills', models.TextField(blank=True, help_text='この職位で求められるスキルや能力', verbose_name='推奨スキル・能力')),
                ('other_requirements', models.TextField(blank=True, verbose_name='その他要件')),
                ('job_description', models.TextField(help_text='具体的な業務内容を記載', verbose_name='主な業務内容')),
                ('responsibilities', models.TextField(help_text='この職位が担う責任範囲', verbose_name='責任範囲')),
                ('authority', models.TextField(blank=True, help_text='この職位に与えられる権限', verbose_name='権限')),
                ('base_salary_min', models.IntegerField(help_text='円', validators=[django.core.validators.MinValueValidator(0)], verbose_name='基本給（最低額）')),
                ('base_salary_max', models.IntegerField(help_text='円', validators=[django.core.validators.MinValueValidator(0)], verbose_name='基本給（最高額）')),
                ('allowances', models.TextField(blank=True, help_text='職務手当、資格手当など', verbose_name='各種手当')),
                ('raise_rules', models.TextField(help_text='定期昇給、号級昇給などのルール', verbose_name='昇給ルール')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_requirements_one', to='facility_management.facility')),
                ('position', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_one', to='career_management.position')),
            ],
            options={
                'verbose_name': 'キャリアパス要件Ⅰ',
                'verbose_name_plural': 'キャリアパス要件Ⅰ（任用要件と賃金体系）',
                'ordering': ['position__level', 'position__job_category'],
            },
        ),
        migrations.CreateModel(
            name='SalaryIncreaseSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_regular_increase', models.BooleanField(default=True, verbose_name='定期昇給の有無')),
                ('increase_timing', models.CharField(choices=[('APRIL', '4月'), ('OCTOBER', '10月'), ('BOTH', '4月・10月（年2回）'), ('OTHER', 'その他')], default='APRIL', max_length=20, verbose_name='定期昇給時期')),
                ('increase_amount_per_step', models.IntegerField(default=1000, help_text='円', validators=[django.core.validators.MinValueValidator(0)], verbose_name='1号級あたりの昇給額')),
                ('max_steps_per_year', models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='年間最大昇給号級数')),
                ('has_special_increase', models.BooleanField(default=False, verbose_name='特別昇給制度の有無')),
                ('special_increase_conditions', models.TextField(blank=True, help_text='資格取得、優秀な評価など', verbose_name='特別昇給の条件')),
                ('evaluation_affects_raise', models.BooleanField(default=True, verbose_name='評価が昇給に影響するか')),
                ('evaluation_criteria', models.TextField(blank=True, help_text='評価と昇給の関係性を記載', verbose_name='評価基準')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_increase_system', to='facility_management.facility')),
            ],
            options={
                'verbose_name': 'キャリアパス要件Ⅲ（昇給制度）',
                'verbose_name_plural': 'キャリアパス要件Ⅲ（昇給制度）',
            },
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.IntegerField(help_text='例：2025', verbose_name='年度')),
                ('training_name', models.CharField(max_length=200, verbose_name='研修名')),
                ('description', models.TextField(help_text='研修の具体的な内容', verbose_name='研修内容')),
                ('objectives', models.TextField(help_text='この研修で達成すべき目標', verbose_name='目標・到達目標')),
                ('scheduled_date', models.DateField(blank=True, null=True, verbose_name='実施予定日')),
                ('training_type', models.CharField(choices=[('OJT', 'OJT（職場内訓練）'), ('OFF_JT', 'Off-JT（職場外訓練）'), ('EXTERNAL', '外部研修'), ('ONLINE', 'オンライン研修')], max_length=20, verbose_name='研修形態')),
                ('duration_hours', models.DecimalField(blank=True, decimal_places=1, help_text='時間', max_digits=4, null=True, verbose_name='研修時間')),
                ('instructor', models.CharField(blank=True, max_length=200, verbose_name='講師・担当者')),
                ('is_mandatory', models.BooleanField(default=False, verbose_name='必須研修')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_plans', to='facility_management.facility')),
                ('target_positions', models.ManyToManyField(related_name='training_plans', to='career_management.position', verbose_name='対象職位')),
            ],
            options={
                'verbose_name': 'キャリアパス要件Ⅱ（研修計画）',
                'verbose_name_plural': 'キャリアパス要件Ⅱ（研修計画）',
                'ordering': ['-fiscal_year', 'scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_date', models.DateField(verbose_name='実施日')),
                ('content', models.TextField(help_text='実際に実施した内容', verbose_name='実施内容')),
                ('evaluation', models.TextField(blank=True, help_text='研修の評価、参加者のフィードバック', verbose_name='評価・フィードバック')),
                ('attachments', models.TextField(blank=True, help_text='資料のファイル名やパスなど', verbose_name='添付資料')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participants', models.ManyToManyField(related_name='training_records', to='career_management.staffmember', verbose_name='参加者')),
                ('training_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='career_management.trainingplan', verbose_name='研修計画')),
            ],
            options={
                'verbose_name': '研修実施記録',
                'verbose_name_plural': '研修実施記録',
                'ordering': ['-actual_date'],
            },
        ),
        migrations.CreateModel(
            name='PromotionCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_experience_years', models.IntegerField(help_text='現職位での経験年数', validators=[django.core.validators.MinValueValidator(0)], verbose_name='必要経験年数')),
                ('required_qualifications', models.TextField(blank=True, help_text='例：介護福祉士、実務者研修修了', verbose_name='必要資格')),
                ('required_evaluation_score', models.DecimalField(blank=True, decimal_places=1, help_text='5段階評価の平均など', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='必要評価点数')),
                ('other_conditions', models.TextField(blank=True, help_text='研修受講、推薦など', verbose_name='その他条件')),
                ('review_process', models.TextField(help_text='面接、実技試験、レポート提出など', verbose_name='昇格審査方法')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_criteria', to='facility_management.facility')),
                ('from_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_from', to='career_management.position', verbose_name='昇格元職位')),
                ('to_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_to', to='career_management.position', verbose_name='昇格先職位')),
            ],
            options={
                'verbose_name': '昇格基準',
                'verbose_name_plural': '昇格基準',
                'ordering': ['from_position__level', 'to_position__level'],
                'unique_together': {('facility', 'from_position', 'to_position')},
            },
        ),
    ]
